apiVersion: v1
kind: ConfigMap
metadata:
  name: online-store-config
data:
  ASPNETCORE_ENVIRONMENT: Production
  Services__OrderServiceBaseUrl: http://order-service:8080
  Services__PaymentServiceBaseUrl: http://payment-service:8080
  Services__ProductServiceBaseUrl: http://product-service:8080
  Services__CartServiceBaseUrl: http://cart-service:8080
  Services__UserServiceBaseUrl: http://user-service:8080
  Services__InventoryServiceGrpcUrl: http://inventory-service:8080
  Services__InventoryGrpcTimeoutSeconds: "3"
  Services__ShippingServiceBaseUrl: http://shipping-service:8080
  Services__HistoryServiceBaseUrl: http://history-service:8080
  Idempotency__TtlMinutes: "1440"
  Auth__JwtIssuer: online-store
  Auth__JwtAudience: online-store-clients
  Auth__RefreshTokenDays: "7"
